### ISSUE TITLE
2022 TODO

### ISSUE THREAD

**Issue by axieax** [MathSocUNSW/mathsoc-website#201]
- [ ] Grace's redesign
- [ ] Competitions - Integration Bee Page
- [ ] Backend / CMS for events/resources
- [ ] Upcoming Events - remove manual window calculation
- [ ] Applications - WAM Calculator, Course Calculator (under resources)
- [ ] LaTeX Guide - embed CodeCogs (see #141) into an iFrame or separate popup?
- [ ] #126
- [ ] NavBar Desktop Dropdown - no fixed width

Some notes:
- Flexbox gap doesn't work on some devices
