### ISSUE TITLE
2021 TODO

### ISSUE THREAD

**Issue by axieax** [MathSocUNSW/mathsoc-website#202]
- [x] Update about us page dotpoint (as per Grace's new design)
- [x] Events pagination (#178)
- [x] Resources - add section for R Guide and Applications
- [ ] Shrink resource strips
