### ISSUE TITLE
2024 TODO

### ISSUE THREAD

**Issue by ericnd** [MathSocUNSW/mathsoc-website#487]
- [ ] update resources for competitions and exam bank
- [ ] update portraits on teams section 
- [ ] update hero image for each page
- [ ] add animations on load
